### ISSUE TITLE
Unable to QUERY ValidationRule, throws GACK error

### ISSUE THREAD

**Issue by chiragmehta84** [afawcett/apex-toolingapi#34]
These days I'm continuously getting GACK error when I try to make a TOOLING API QUERY call.This used to work earlier.

/services/data/v33.0/tooling/query/?q=Select+Id%2C+FullName+FROM+ValidationRule+limit+100 
gives error: An unexpected error occurred. Please include this ErrorId if you contact support: 1269173235-153226 (-6049864)

Am I missing something? or it's really a GACK ie salesforce issue around tooling api for ValidationRule?

**Comment by afawcett** [comment]
@chiragmehta84 so sorry for not getting back sooner...

I've not tried this recently, are you using the REST or SOAP based wrapper?

**Comment by chiragmehta84** [comment]
REST based wrapper (earlier one).

**Comment by afawcett** [comment]
Ok in this case, that sounds like the REST API may have changed under the wrappers feet, though in theory the SF API backwards compatibility should avoid this. As its an undocumented error my recommendation is to reproduce the error, grab the actual URL from the debug log, reproduce it via Developer Work Bench REST tool, record the steps and send over to Salesforce Support. Reason i suggest this, is it avoids SF support focusing on the Apex wrapper side rather than the root cause. Keep me posted on what they say! :+1:
